name: ZAP
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: owasp/zap2docker-stable
      options: --user root
      volumes:
        - $(pwd):/zap/wrk/:rw
    steps:
      - uses: actions/checkout@v1
      - name: view file
        run: pwd
      - name: run zap
        if: always()
        run: zap-baseline.py -t https://www.example.com
      - name: view file
        run: pwd
