name: ZAP
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: owasp/zap2docker-stable
      options: --user root -v /__w/actions-test-repo/actions-test-repo/:/zap/wrk/
      volumes:
        - /__w/actions-test-repo/:/zap/wrk/
    steps:
      - uses: actions/checkout@v1
      - name: run zap
        if: always()
        run: zap-baseline.py -t https://www.example.com -g gen.conf -r testreport.html
#       - name: Run any additional scripts to raise issues etc
      - name: view file
        if: always()
        run: pwd
      - name: nav
        if: always()
        run: cd /home/runner/work/actions-test-repo/actions-test-repo/
      - name: ls
        if: always()
        run: ls
      - name: read
        if: always()
        run: cat zap.out
