name: ZAP
on: push
jobs:
  scan:
    runs-on: ubuntu-latest
    container:
      image: owasp/zap2docker-stable
      options: --user root -v ${{ github.workspace }}:/zap/wrk/:rw
    steps:
      - uses: actions/checkout@v2
      - run: pwd && ls -l
      - run: pip3 install --upgrade pip github3.py
      - run: python3 custom.py
      - run: echo $PYTHONPATH  
      - name: run zap baseline scan
        run: zap-baseline.py -t https://example.com -x report_xml.xml --hook=/zap/wrk/custom.py || echo 0
      - run: pwd && ls -l /zap/wrk/
      - run: cat /zap/wrk/report_xml.xml
