name: ZAP
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: sshniro/zap_action
      options: --user root -v /__w/actions-test-repo/actions-test-repo:/zap/wrk:rw -v /var/run/docker.sock:/var/run/docker.sock
    steps:
      - uses: actions/checkout@v1
      - name: run zap baseline scan
        if: always()
        run: zap-baseline.py -t https://www.zaproxy.org -x report_xml.xml -c /.github/workflows/rules.tsv -k
      - name: check the present working dir and read the zap log file
        if: always()
        run: pwd && ls && cat zap.out
      - name: read the xml file
        if: always()
        run: cd /github/home && ls && cat report_xml.xml
      - name: ls the roon folder
        if: always()
        run: cd /__w/ && ls
