name: ZAP
on:
  push:
    paths-ignore:
      - '.zap/**'
jobs:

  scan:
    runs-on: ubuntu-latest
    container:
      image: owasp/zap2docker-stable
      options: --user root -v ${{ github.workspace }}:/zap/wrk/:rw
    steps:
      - uses: actions/checkout@v2
      - run: pwd && ls -l
      - run: pip install --upgrade pip PyGithub pyyaml deepdiff
      - run: pip3 install --upgrade pip PyGithub pyyaml deepdiff
      - name: run zap baseline scan
        run: zap-baseline.py -t https://example.com -J report_json.json --hook=/zap/wrk/.github/workflows/custom.py || echo 0
      - run: pwd && ls -l /zap/wrk/
      - name: run custom script
        run: python3 /zap/wrk/custom.py
        env:
          GITHUB_TOKEN: ${{ secrets.GIT_TOKEN }}
          YAML_FILE_NAME: zap_report.yml
          WORKING_BRANCH: master

      - run: cat /zap/wrk/report_json.json
