name: ZAP
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: sshniro/zap_action
      options: --user root -v /__w/actions-test-repo/actions-test-repo:/zap/wrk/:rw -v /var/run/docker.sock:/var/run/docker.sock
    steps:
      - uses: actions/checkout@v1
      - name: run zap baseline scal
        if: always()
        run: zap-baseline.py -t https://www.example.com -g gen.conf -r testreport.html
      - name: check the present working dir
        if: always()
        run: pwd
      - name: nav
        if: always()
        run: cd /__w/
      - name: list all the files in the directory
        if: always()
        run: ls
      - name: read zap output file
        if: always()
        run: cat zap.out
      - name: nav
        if: always()
        run: cd /github/home
      - name: list all the files in the directory
        if: always()
        run: ls
